#!/usr/bin/python
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver import ActionChains
import requests
import sys

while(1):
    try:
        html = requests.get("https://www.baidu.com",timeout=2)
    except:
        try:
            driver = webdriver.Chrome()
            driver.get("http://10.253.0.237/")
            elem = driver.find_element_by_id("username")
            elem.clear()
            elem.send_keys("201921100325")
            elem.send_keys(Keys.RETURN)
            elem = driver.find_element_by_id("password")
            elem.clear()
            elem.send_keys("1234QWER")
            elem.send_keys(Keys.RETURN)
            message = 'reconnect_date%s'\
                    %time.strftime("%Y-%m-%d %H:%M:%S\n",time.localtime())
            f = open("/home/oycq/tools/autoconnect.log", "a")
            f.write(message)
            f.close()
            print('reconnect_date%s'%time.strftime("%Y-%m-%d %H:%M:%S",time.localtime()))
        except:
            pass
        time.sleep(5)
        driver.close()
    time.sleep(60)
